import type { CharacterDef, OutfitDef, GunDef, SkillDef, GadgetDef, MonsterDef } from "./types";
import gunsData from "../../data/guns.json";

// ---------------------------------------------------------------------------
// CHARACTERS — different builds with their own stat profiles & color identity.
// ---------------------------------------------------------------------------
export const CHARACTERS: CharacterDef[] = [
  {
    id: "raider",
    name: "突袭者",
    title: "Raider",
    bodyColor: "#00f0ff",
    accent: "#0284c7",
    skin: "#fed7aa",
    speed: 235,
    maxHp: 100,
    damageMult: 1.0,
    fireRateMult: 1.0,
    size: 16,
    perk: "攻防均衡，适应全战局",
    desc: "全能型特工，手感均衡无短板。",
  },
  {
    id: "juggernaut",
    name: "重装兵",
    title: "Juggernaut",
    bodyColor: "#10b981",
    accent: "#047857",
    skin: "#fdba74",
    speed: 178,
    maxHp: 165,
    damageMult: 0.92,
    fireRateMult: 0.95,
    size: 19,
    perk: "超高血量，移速较低",
    desc: "移动堡垒，极高容错与抗击退。",
  },
  {
    id: "phantom",
    name: "灵狐",
    title: "Phantom",
    bodyColor: "#f43f5e",
    accent: "#be123c",
    skin: "#fed7aa",
    speed: 296,
    maxHp: 72,
    damageMult: 1.12,
    fireRateMult: 1.18,
    size: 14,
    perk: "极速高伤，脆弱身板",
    desc: "突刺刺客，靠高速走位与爆发撕裂敌阵。",
  },
  {
    id: "sentinel",
    name: "哨兵",
    title: "Sentinel",
    bodyColor: "#f59e0b",
    accent: "#b45309",
    skin: "#fed7aa",
    speed: 214,
    maxHp: 96,
    damageMult: 1.28,
    fireRateMult: 0.86,
    size: 16,
    perk: "重火力强化，射速稍慢",
    desc: "重炮手，单发威力与穿甲表现出众。",
  },
];

// ---------------------------------------------------------------------------
// OUTFITS — cosmetic color schemes + headgear, each with a minor stat bonus.
// ---------------------------------------------------------------------------
export const OUTFITS: OutfitDef[] = [
  {
    id: "tactical",
    name: "经典战术",
    suit: "#475569",
    suitDark: "#1e293b",
    accent: "#f8fafc",
    hat: "helmet",
    perk: "基础防具",
    speedBonus: 0,
    hpBonus: 0,
  },
  {
    id: "night",
    name: "暗夜潜行",
    suit: "#4338ca",
    suitDark: "#1e1b4b",
    accent: "#a5b4fc",
    hat: "hood",
    perk: "移速 +6%",
    speedBonus: 0.06,
    hpBonus: 0,
  },
  {
    id: "desert",
    name: "沙漠风暴",
    suit: "#f59e0b",
    suitDark: "#b45309",
    accent: "#fef3c7",
    hat: "cap",
    perk: "基础防具",
    speedBonus: 0,
    hpBonus: 0,
  },
  {
    id: "neon",
    name: "霓虹猎手",
    suit: "#0f172a",
    suitDark: "#020617",
    accent: "#00f0ff",
    hat: "visor",
    perk: "射速 +6%",
    speedBonus: 0,
    hpBonus: 0,
    fireRateBonus: 0.06,
  },
  {
    id: "crimson",
    name: "赤焰斗士",
    suit: "#dc2626",
    suitDark: "#7f1d1d",
    accent: "#fecaca",
    hat: "cap",
    perk: "移速 +4% · 生命 +6",
    speedBonus: 0.04,
    hpBonus: 6,
  },
  {
    id: "emerald",
    name: "翡翠卫士",
    suit: "#16a34a",
    suitDark: "#14532d",
    accent: "#86efac",
    hat: "helmet",
    perk: "基础防具",
    speedBonus: 0,
    hpBonus: 0,
  },
  // ===================== SKINS (this update) =====================
  {
    id: "alien",
    name: "外星人 👽",
    suit: "#22d3ee",
    suitDark: "#0e7490",
    accent: "#a5f3fc",
    hat: "alien",
    perk: "移速 +6%",
    speedBonus: 0.06,
    hpBonus: 0,
    skin: "#7ef0b0",
  },
  {
    id: "monkey",
    name: "猴子 🐒",
    suit: "#a16207",
    suitDark: "#854d0e",
    accent: "#fbbf24",
    hat: "monkey",
    perk: "生命 +18",
    speedBonus: 0,
    hpBonus: 18,
    skin: "#caa072",
  },
  {
    id: "tycoon",
    name: "大亨 🎩",
    suit: "#4c1d95",
    suitDark: "#2e1065",
    accent: "#fbbf24",
    hat: "tycoon",
    perk: "射速 +5%",
    speedBonus: 0,
    hpBonus: 0,
    fireRateBonus: 0.05,
  },
  {
    id: "medic",
    name: "战地医疗兵",
    suit: "#f8fafc",
    suitDark: "#cbd5e1",
    accent: "#ef4444",
    hat: "helmet",
    perk: "生命 +12",
    speedBonus: 0,
    hpBonus: 12,
  },
  {
    id: "cyber_ninja",
    name: "赛博忍者",
    suit: "#0f172a",
    suitDark: "#020617",
    accent: "#4ade80",
    hat: "hood",
    perk: "移速 +8%",
    speedBonus: 0.08,
    hpBonus: 0,
  },
  {
    id: "pirate",
    name: "星际海盗",
    suit: "#78350f",
    suitDark: "#451a03",
    accent: "#fbbf24",
    hat: "cap",
    perk: "射速 +4% · 移速 +2%",
    speedBonus: 0.02,
    hpBonus: 0,
    fireRateBonus: 0.04,
  },
  {
    id: "royal_guard",
    name: "皇家卫士",
    suit: "#7f1d1d",
    suitDark: "#450a0a",
    accent: "#fcd34d",
    hat: "visor",
    perk: "生命 +15",
    speedBonus: 0,
    hpBonus: 15,
  },
  {
    id: "hazard",
    name: "防化清道夫",
    suit: "#eab308",
    suitDark: "#a16207",
    accent: "#171717",
    hat: "visor",
    perk: "基础防具",
    speedBonus: 0,
    hpBonus: 0,
  },
  {
    id: "ghost",
    name: "幽灵特工",
    suit: "#f8fafc",
    suitDark: "#94a3b8",
    accent: "#60a5fa",
    hat: "hood",
    perk: "移速 +5% · 射速 +3%",
    speedBonus: 0.05,
    hpBonus: 0,
    fireRateBonus: 0.03,
  },
];

// ---------------------------------------------------------------------------
// GUNS — distinct weapon archetypes with very different feel.
// 游戏中按 E 循环切换武器；半自动武器(semiAuto)需松开左键后才能再次开火。
// ---------------------------------------------------------------------------
// GUNS data lives in data/guns.json (edit via `npm run editor`) so every
// build target — client bundle AND server engine bundle — shares one source.
export const GUNS: GunDef[] = gunsData as unknown as GunDef[];

// ---------------------------------------------------------------------------
// SKILLS — activated with Q, each on a cooldown.
// ---------------------------------------------------------------------------
export const SKILLS: SkillDef[] = [
  {
    id: "dash",
    name: "冲刺闪避",
    desc: "高速突进无敌（蓄力3段）",
    cooldown: 5,
    duration: 0.28,
    color: "#22d3ee",
    icon: "⚡",
  },
  {
    id: "shield",
    name: "能量护盾",
    desc: "短暂免疫一切伤害",
    cooldown: 7,
    duration: 2.4,
    color: "#60a5fa",
    icon: "🛡️",
  },
  {
    id: "timewarp",
    name: "时间扭曲",
    desc: "全局减速所有敌人",
    cooldown: 8.5,
    duration: 3.5,
    color: "#c084fc",
    icon: "⏳",
  },
  {
    id: "grenade",
    name: "投掷手雷",
    desc: "准星方向投掷范围爆破",
    cooldown: 4,
    duration: 0.5,
    color: "#f97316",
    icon: "💣",
  },
  {
    id: "overdrive",
    name: "火力过载",
    desc: "大幅提升武器射速",
    cooldown: 9,
    duration: 4,
    color: "#fbbf24",
    icon: "🔥",
  },
  {
    id: "charge_slam",
    name: "冲撞砸击",
    desc: "破障冲撞，二次触发砸地爆裂",
    cooldown: 8,
    duration: 1.6,
    color: "#f97316",
    icon: "🐗",
  },
  {
    id: "cloak",
    name: "隐身装置",
    desc: "静止隐身，耗能，受击破隐",
    cooldown: 1.5,
    duration: 0,
    isEnergy: true,
    maxEnergy: 100,
    color: "#a855f7",
    icon: "👤",
  },
  {
    id: "winch_claw",
    name: "绞盘铁爪",
    desc: "射爪抓取敌方并造成僵直",
    cooldown: 7,
    duration: 0.5,
    color: "#eab308",
    icon: "⚓",
  },
];

// ---------------------------------------------------------------------------
// GADGETS — deployable tactical items, each on its own cooldown.
// Activated in-game via the gadget bar (keys F1..F6 or click).
// ---------------------------------------------------------------------------
export const GADGETS: GadgetDef[] = [
  {
    id: "turret_mg",
    kind: "turret_mg",
    name: "哨戒机枪",
    desc: "自动索敌持续机枪射击",
    cooldown: 16,
    iconShape: "turret_mg",
    color: "#38bdf8",
    maxStack: 3,
    hp: 176,
  },
  {
    id: "turret_cannon",
    kind: "turret_cannon",
    name: "哨戒炮塔",
    desc: "范围连发轻型炸弹炮击",
    cooldown: 20,
    iconShape: "turret_cannon",
    color: "#a78bfa",
    maxStack: 2,
    hp: 220,
  },
  {
    id: "mine_explosive",
    kind: "mine_explosive",
    name: "爆炸地雷",
    desc: "踩踏引爆，强力范围伤害",
    cooldown: 30,
    iconShape: "mine_explosive",
    color: "#f87171",
    maxStack: 4,
  },
  {
    id: "mine_poison",
    kind: "mine_poison",
    name: "毒气地雷",
    desc: "触发释放范围减速毒云",
    cooldown: 20,
    iconShape: "mine_poison",
    color: "#84cc16",
    maxStack: 4,
  },
  {
    id: "mine_fire",
    kind: "mine_fire",
    name: "火焰地雷",
    desc: "触发生成持续燃烧火场",
    cooldown: 20,
    iconShape: "mine_fire",
    color: "#fb923c",
    maxStack: 4,
  },
  {
    id: "glue_grenade",
    kind: "glue_grenade",
    name: "粘胶手雷",
    desc: "投掷生成阻挡减速粘胶墙",
    cooldown: 20,
    iconShape: "glue_grenade",
    color: "#22d3ee",
    maxStack: 3,
  },
  {
    id: "fire_grenade",
    kind: "fire_grenade",
    name: "火焰手雷",
    desc: "投掷生成大片持续火场",
    cooldown: 22,
    iconShape: "fire_grenade",
    color: "#fb923c",
    maxStack: 3,
  },
  {
    id: "poison_grenade",
    kind: "poison_grenade",
    name: "毒气手雷",
    desc: "投掷生成滞留腐蚀毒云",
    cooldown: 20,
    iconShape: "poison_grenade",
    color: "#84cc16",
    maxStack: 3,
  },
  {
    id: "healing_station",
    kind: "healing_station",
    name: "治疗站",
    desc: "部署后范围持续恢复生命",
    cooldown: 25,
    iconShape: "healing_station",
    color: "#4ade80",
    maxStack: 2,
    hp: 80,
  },
  {
    id: "healing_beam",
    kind: "healing_beam",
    name: "治疗射线",
    desc: "持续治疗友军，注意过热",
    cooldown: 0,
    iconShape: "healing_beam",
    color: "#60a5fa",
    healPerSecond: 50,
    heatPerSecond: 1 / 5,
    coolRate: 1 / 4,
  },
  {
    id: "rpg",
    kind: "rpg",
    name: "RPG-7",
    desc: "发射高爆火箭，超大范围重伤",
    cooldown: 35,
    iconShape: "rpg",
    color: "#ef4444",
    projectileDamage: 140,
    explosionRadius: 360,
    projectileSpeed: 800,
  },
  {
    id: "stun_gun",
    kind: "stun_gun",
    name: "电击枪",
    desc: "命中使目标瘫痪3秒",
    cooldown: 18,
    iconShape: "stun_gun",
    color: "#fde047",
    projectileDamage: 20,
    projectileSpeed: 1000,
    ccDuration: 3.0,
  },
  {
    id: "turret_sniper",
    kind: "turret_sniper",
    name: "狙击炮塔",
    desc: "红外穿透狙击，极高单发伤害",
    cooldown: 25,
    iconShape: "turret_sniper",
    color: "#f43f5e",
    maxStack: 2,
    hp: 120,
  },
  {
    id: "mine_stun",
    kind: "mine_stun",
    name: "震撼地雷",
    desc: "范围引爆，瘫痪范围内敌人",
    cooldown: 22,
    iconShape: "mine_stun",
    color: "#fde047",
    maxStack: 3,
  },
  {
    id: "cluster_grenade",
    kind: "cluster_grenade",
    name: "集束手雷",
    desc: "爆裂后分裂4枚子母炸弹",
    cooldown: 28,
    iconShape: "cluster_grenade",
    color: "#f97316",
    maxStack: 2,
  },
];

// ---------------------------------------------------------------------------
// MONSTERS — biohazard (生化危机) bestiary.
// ---------------------------------------------------------------------------
export const MONSTERS: MonsterDef[] = [
  {
    id: "walker",
    name: "行尸",
    behavior: "walker",
    desc: "近战普通丧尸，群体行动",
    hp: 75,
    speed: 64,
    damage: 12,
    size: 15,
    color: "#7c9c5a",
    glow: "#a3e635",
    score: 12,
    weight: 3,
  },
  {
    id: "runner",
    name: "奔尸",
    behavior: "runner",
    desc: "极速奔袭，周期性飞扑撕咬",
    hp: 55,
    speed: 150,
    damage: 10,
    size: 13,
    color: "#a3e635",
    glow: "#bef264",
    score: 16,
    weight: 2,
  },
  {
    id: "brute",
    name: "巨尸",
    behavior: "brute",
    desc: "重甲肉盾，重击沉重带击退",
    hp: 460,
    speed: 40,
    damage: 30,
    size: 30,
    color: "#4d7c4d",
    glow: "#65a30d",
    score: 60,
    weight: 1,
  },
  {
    id: "spitter",
    name: "吐酸者",
    behavior: "spitter",
    desc: "远程喷吐酸液，保持距离",
    hp: 110,
    speed: 56,
    damage: 10,
    size: 17,
    color: "#a78bfa",
    glow: "#c084fc",
    score: 35,
    ranged: true,
    rangedRange: 360,
    rangedDamage: 14,
    weight: 1.4,
  },
  {
    id: "abomination",
    name: "母体",
    behavior: "abomination",
    desc: "巨型BOSS，砸地重击，死后殉爆",
    hp: 2600,
    speed: 30,
    damage: 45,
    size: 46,
    color: "#7e22ce",
    glow: "#a855f7",
    score: 400,
    weight: 0.4,
    minWave: 6,
  },
  {
    id: "crawler",
    name: "爬虫",
    behavior: "crawler",
    desc: "微型成群，高速贴地偷袭",
    hp: 30,
    speed: 205,
    damage: 7,
    size: 10,
    color: "#d9f99d",
    glow: "#bef264",
    score: 8,
    weight: 1.6,
  },
  {
    id: "bloater",
    name: "毒爆体",
    behavior: "bloater",
    desc: "臃肿毒囊，击杀扩散剧毒云",
    hp: 190,
    speed: 46,
    damage: 14,
    size: 26,
    color: "#65a30d",
    glow: "#a3e635",
    score: 40,
    explodeRadius: 130,
    explodeDamage: 60,
    weight: 0.9,
    minWave: 2,
  },
  {
    id: "screamer",
    name: "尖啸者",
    behavior: "screamer",
    desc: "尖啸狂暴尸群，震慑特工",
    hp: 130,
    speed: 72,
    damage: 8,
    size: 18,
    color: "#f0abfc",
    glow: "#e879f9",
    score: 45,
    buffRadius: 270,
    weight: 0.8,
    minWave: 3,
  },
  {
    id: "spore",
    name: "孢子怪",
    behavior: "spore",
    desc: "自发毒雾，靠近持续中毒",
    hp: 165,
    speed: 50,
    damage: 10,
    size: 20,
    color: "#a3e635",
    glow: "#84cc16",
    score: 38,
    cloudRadius: 95,
    cloudDamage: 42,
    weight: 0.9,
    minWave: 2,
  },
];

export const getMonster = (id: string) =>
  MONSTERS.find((m) => m.id === id) ?? MONSTERS[0];

export const getCharacter = (id: string) =>
  CHARACTERS.find((c) => c.id === id) ?? CHARACTERS[0];
export const getOutfit = (id: string) =>
  OUTFITS.find((o) => o.id === id) ?? OUTFITS[0];
export const getGun = (id: string) => GUNS.find((g) => g.id === id) ?? GUNS[0];
/** Like getGun but returns undefined when the id doesn't match any weapon in guns.json.
 *  Use this in UI code where you need to distinguish "real weapon" from "generic attack". */
export const findGun = (id: string): GunDef | undefined => GUNS.find((g) => g.id === id);
export const getSkill = (id: string) =>
  SKILLS.find((s) => s.id === id) ?? SKILLS[0];
export const getGadget = (id: string) =>
  GADGETS.find((g) => g.id === id) ?? GADGETS[0];

// ---------------------------------------------------------------------------
// SCENES — visual themes for different arena environments.
// ---------------------------------------------------------------------------
export interface SceneTheme {
  id: string;
  name: string;
  bgTop: string;
  bgBottom: string;
  wallColor: string;
  wallDark: string;
  accent: string;
  /** "grid" = flat neon grid floor (default); "city" = top-down cyber-city blocks */
  style?: "grid" | "city" | "ruin" | "organic" | "ice";
  /** override grid line color (used by cyber style) */
  gridColor?: string;
}

export const SCENES: SceneTheme[] = [
  {
    id: "neon",
    name: "霓虹都市",
    bgTop: "#1e1b4b",
    bgBottom: "#0f172a",
    wallColor: "#4338ca",
    wallDark: "#1e1b4b",
    accent: "#818cf8",
  },
  {
    id: "desert",
    name: "沙漠废墟",
    bgTop: "#451a03",
    bgBottom: "#290c01",
    wallColor: "#d97706",
    wallDark: "#78350f",
    accent: "#fbbf24",
  },
  {
    id: "arctic",
    name: "冰原基地",
    bgTop: "#0c2b4d",
    bgBottom: "#051628",
    wallColor: "#0284c7",
    wallDark: "#075985",
    accent: "#38bdf8",
  },
  {
    id: "ruin",
    name: "末日废墟",
    bgTop: "#450a0a",
    bgBottom: "#260404",
    wallColor: "#b91c1c",
    wallDark: "#7f1d1d",
    accent: "#f87171",
  },
  {
    id: "cyber",
    name: "赛博都市",
    bgTop: "#0b0826",
    bgBottom: "#03020c",
    wallColor: "#2563eb",
    wallDark: "#1e3a8a",
    accent: "#00f0ff",
    style: "city",
    gridColor: "rgba(0,240,255,0.15)",
  },
  {
    id: "wild_west",
    name: "西部牛仔",
    bgTop: "#d97706",
    bgBottom: "#92400e",
    wallColor: "#b45309",
    wallDark: "#78350f",
    accent: "#fde047",
    style: "ruin",
    gridColor: "rgba(253,224,71,0.18)",
  },
  {
    id: "jungle",
    name: "幽静丛林",
    bgTop: "#14532d",
    bgBottom: "#052e16",
    wallColor: "#16a34a",
    wallDark: "#14532d",
    accent: "#4ade80",
    style: "organic",
    gridColor: "rgba(74,222,128,0.15)",
  },
  {
    id: "arctic_zone",
    name: "极寒地带",
    bgTop: "#60a5fa",
    bgBottom: "#dbeafe",
    wallColor: "#93c5fd",
    wallDark: "#3b82f6",
    accent: "#0284c7",
    style: "ice",
    gridColor: "rgba(2,132,199,0.25)",
  },
];
