// Encodes the "灵狐" (phantom) character wav sfx from the 908 folder into a
// base64 data-URI module so the single-file production build needs no external
// asset requests. Run from the project root: `node scripts/gen_sfx.mjs`.
import fs from "node:fs";
import path from "node:path";

const SRC = "c:/Users/86139/Desktop/908";
// hit pool = 7月17日 0..5 ; death = Death.WAV
const map = {
  hit0: "7月17日（0）.WAV",
  hit1: "7月17日(1).WAV",
  hit2: "7月17日(2).WAV",
  hit3: "7月17日(3).WAV",
  hit4: "7月17日(4).WAV",
  hit5: "7月17日(5).WAV",
  death: "Death.WAV",
};

const b64 = (f) => fs.readFileSync(path.join(SRC, f)).toString("base64");

const hits = [map.hit0, map.hit1, map.hit2, map.hit3, map.hit4, map.hit5].map(b64);
const death = b64(map.death);

let out = "";
out += `// AUTO-GENERATED by scripts/gen_sfx.mjs -- do not edit by hand.\n`;
out += `// Base64 data-URI wav clips for the "灵狐" (phantom) character, inlined so the\n`;
out += `// single-file production build needs no external asset requests.\n`;
out += `export interface CharSfx { hit: string[]; death: string }\n`;
out += `export const SFX: Record<string, CharSfx> = {\n`;
out += `  phantom: {\n`;
out += `    hit: [\n`;
for (const h of hits) out += `      "data:audio/wav;base64,${h}",\n`;
out += `    ],\n`;
out += `    death: "data:audio/wav;base64,${death}",\n`;
out += `  },\n`;
out += `};\n`;

const dest = path.join(process.cwd(), "src/game/sfxData.ts");
fs.writeFileSync(dest, out);
console.log(
  `sfxData.ts written (${hits.map((h) => h.length).join(", ")} , death ${death.length} base64 chars)`
);
